### ISSUE TITLE
I need help with Summit Gem Manager

### ISSUE THREAD

**Issue by takeshipoggies** [CommunalHelper/CommunalHelper#131]
- [x] My mods and Everest install are up to date.
- [x] I have recreated the bug with *only* CommunalHelper OR a minimum number of other mods enabled.

**Describe the bug**
2 different problems:
- I can't set the Gems Ids option to (roomName/index)
- I can set the Gems Ids option to just (index) but I can't trigger the Summit Gem Manager event (the nodes aren't exploding, nor the heart is moving).

**To Reproduce**
I set up a Summit Gem Manager, set Gems Ids as above, but either I can't save changes if I use the syntax (roomName/index)
![Screenshot 2023-02-14 150535](https://user-images.githubusercontent.com/62186122/218762273-59c8010f-080a-401a-8cd2-d71e4844a6f9.png)
or I can save changes using the (index) syntax but the event doesn't trigger
![Screenshot 2023-02-14 151238](https://user-images.githubusercontent.com/62186122/218763200-a3061393-0c44-492e-a831-c2fcb695b2c2.png)
https://user-images.githubusercontent.com/62186122/218764902-db9440ce-0623-4103-a86d-1be01fcfa674.mp4

**Expected behavior**
I should see the vessels of the gems, created with nodes, start exploding signifying the collection of said gems and the heart moving from up there to the position of the Manager.

**System Info(please complete the following information):**
 - OS: Windows 11

**Additional context**
The game doesn't crash, it just doesn't recognize I collected the gems.
I also tried using different hearts but the result is the same, and I assume it doesn't matter anyway, in terms of triggering the event.
I also tried using the $ symbol as shown in the helper's Wiki page, but yet again it doesn't let me save changes.
I don't know if I'm missing some triggers or other stuff, but I checked other maps that use the manager and it works fine, while having the exact same Map and Room options and setup as mine.
My mod directory looks like this in case it makes some difference.
__Mods
____TestMod
______Maps
________Takeshi
__________TestMod
____________testmap2.bin

IMPORTANT update as of writing this, I checked in another map, specifically the level Summit from the mod Staticleste, which successfully uses the syntax (roomName/index) and after clearing the Gems Ids option to type it again exactly how it was, it didn't let me save changes there either.
At this point I suppose it could also be a bug concerning Loenn...
For context my version of Loenn is the latest as of writing this, which is v0.5.1

**Comment by catapillie** [comment]
Thanks for reporting. The reason you're unable to use the custom room syntax is because the Lönn plugin expects the `gemIds` field to be a comma-separated list of strictly positive integers, which is incorrect (and my fault).

I'll be pushing an update to allow for custom room syntax, and hopefully then you should be able to get your Summit Gem Manager working.

**Comment by takeshipoggies** [comment]
Thank you for the extremely speedy reply ^^
I tested everything I could test, now it works flawlessly.

I have nothing else to report so I guess I can close this.
Also thanks for creating this wonderful helper. we love it.
