### ISSUE TITLE
Railed Move Block: static mover depth

### ISSUE THREAD

**Issue by catapillie** [CommunalHelper/CommunalHelper#132]
Add an option to Railed Move Blocks that make its static movers appear in front of the move block buttons. This can be done by modifying their depth, which are set to the block's depth since they are static movers.

- [x] Is your request a change to an existing feature?
  - **Railed Move Blocks**

**Additional details:**
No additional details. This is pretty straight-forward.

**Comment by MorkyPep** [comment]
this issue has been addressed in my new PR.
