### ISSUE TITLE
Dash Magnet

### ISSUE THREAD

**Issue by cellularAutomaton** [CommunalHelper/CommunalHelper#133]
[Someone else is currently working on this idea - not that i shopped it around or something, the coder asked me for entity ideas - so don't worry about it anymore. Closing the issue as not planned.]

**Comment by l-Luna** [comment]
Angled dashes already have interactions with tech (and their own new ones), so I don't think changing those is worth it.

What might also be interesting is a weaker version of the magnet which curves dashes towards it, as if you held that direction under superdash but stronger. This still provides interesting 360 degree dashes, while providing more gameplay options (you can dash in multiple directions) and more obvious interaction with superdash; in particular, you also get superdash-style tech, like starting an upwards/downwards dash and having it curved down/up for an ultra/vertical speed boost.

**Comment by cellularAutomaton** [comment]
Interesting, I didn't know there was already 360 dashing tech! That makes the case for a Dash Magnet more compelling, since it would allow keyboard players to execute this tech.

**Comment by l-Luna** [comment]
The game handles angled dashes as the closest normal direction for tech purposes, at the moment where the dash ends or you press jump. Normal 360 dashes don't allow for anything new, but curved superdashes can start at one direction and count as something different, which is where new tech comes in; so I think curving dashes is more interesting.

**Comment by cellularAutomaton** [comment]
My main concern with the curved dashes is that it would introduce a lot of inconsistency compared to 360 dashing, since you might not get curved all the way to the center.
