### ISSUE TITLE
Dream Jelly Feather Noise bug

### ISSUE THREAD

**Issue by fogrobin** [CommunalHelper/CommunalHelper#138]
- [x] My mods and Everest install are up to date.
- [ ] I have recreated the bug with *only* CommunalHelper OR a minimum number of other mods enabled.

**Describe the bug**

This is an audio bug. After using a dream jellyfish, if the player enters feather state and then dies to a hazard in feather state, the feather noise persists beyond death. This can even stack with multiple deaths. It does not happen with other dream block mechanics. 

**To Reproduce**
Provide a description, screenshots, video, and/or map containing the issue.

1. Dash through dream jellyfish.
2. Enter feather state via feather, feather refill, feather bumper, etc.
3. Die to a hazard while in the feather state.
4. Listen to the feather noise, it persists and does not stop.
5. Repeat process without refreshing map or using debug to stack the effect. 

Here is a video: https://streamable.com/w8d5lr

**Expected behavior**
A clear description of what you expected to happen.

I expected the feather noise to stop after dying, as the player is no longer in feather state. 

**System Info(please complete the following information):**
 - OS: [e.g. Windows, Linux, Mac]

I use Windows 10

**Additional context**
Make sure to upload any game logs or crash reports.

**Comment by catapillie** [comment]
Should be fixed as of 7db45951c29cebcd4cb80849ed797e4fa7d8787b
