### ISSUE TITLE
Elytra keybind keyword for tutorials

### ISSUE THREAD

**Issue by catapillie** [CommunalHelper/CommunalHelper#154]
We need a keyword for displaying elytra keybinds in tutorial birds and similar.

- [x] Is your request a change to an existing feature?
  - Elytra / (Everest bird tutorial parsing event)

**Comment by mayromr** [comment]
I'll take a look at this

**Comment by vivianlonging** [comment]
`mod:CommunalHelper/DeployElytra` works out of the box, closed.
(Also this works for every modded binding option that is in a Settings tab in the form `mod:$ModName/$BindingNameInSettings`)
