### ISSUE TITLE
Large connected dream blocks cause a lot of lag

### ISSUE THREAD

**Issue by JaThePlayer** [CommunalHelper/CommunalHelper#176]
Having large connected dream blocks causes a lot of rendering lag, as can be seen here:
https://discord.com/channels/403698615446536203/908809001834274887/1191797084169437224

This is mostly related to particle rendering, which is currently not camera-culled at all. Would be nice to add some here, using `Celeste.Mod.Helpers.CullHelper.IsRectangleVisible`
https://github.com/CommunalHelper/CommunalHelper/blob/c2c6bde9f20dd2bcf77b9483c7fd561d74cccacf/src/Entities/DreamBlocks/ConnectedDreamBlock.cs#L442-L502

**Comment by jorje15** [comment]
i love you
