### ISSUE TITLE
new bug after fix crash

### ISSUE THREAD

**Issue by liushengqi000** [CommunalHelper/CommunalHelper#54]
shade world 1.2.1 & communal Helper 1.71 

![shade world 1.2.1 & communal Helper 1.71 ](https://user-images.githubusercontent.com/1914238/120936529-d88bc000-c73a-11eb-83e8-023d4e00fcf7.png)

shade world 1.2.1 & communal Helper 1.82 

![shade world 1.2.1 & communal Helper 1.82 ](https://user-images.githubusercontent.com/1914238/120936532-db86b080-c73a-11eb-9104-a74b4f0f5f4a.png)

where is the dream block?

_Originally posted by @liushengqi000 in https://github.com/CommunalHelper/CommunalHelper/issues/47#issuecomment-855444789_

[log_comunalhelper171.txt](https://github.com/CommunalHelper/CommunalHelper/files/6604726/log_comunalhelper171.txt)
[log_comunalhelper182.txt](https://github.com/CommunalHelper/CommunalHelper/files/6604727/log_comunalhelper182.txt)

**Comment by liushengqi000** [comment]
i removed all mods and reinstalled communalhelper.
it still doesn't work.
[log.txt](https://github.com/CommunalHelper/CommunalHelper/files/6614936/log.txt)

**Comment by coloursofnoise** [comment]
That log is for `1.8.2`, CommunalHelper was updated today with a fix for this issue, with the version number `1.8.3`.

**Comment by liushengqi000** [comment]
> That log is for `1.8.2`, CommunalHelper was updated today with a fix for this issue, with the version number `1.8.3`.

everything is OK. 
thank you very much. 
^_^
