### ISSUE TITLE
Non-outlined chains regain outlines when broken

### ISSUE THREAD

**Issue by Mosscairn** [CommunalHelper/CommunalHelper#76]
Hello, just noticed that chains regain their outlines when broken. Here's an example, all of these have outlines disabled but outlines will appear immediately once they're split in two. Hope this helps!
![image](https://user-images.githubusercontent.com/54695659/131265241-00926fed-a8d5-40db-ae43-1c0d5afb7920.png)
![image](https://user-images.githubusercontent.com/54695659/131265317-cb408a8f-eab3-42bc-a829-26f79a75265e.png)

**Comment by catapillie** [comment]
Fixed in 92d74ff8536258f2b7fc43e717e28aaf7cb5cce3.
