### ISSUE TITLE
Station Mover blocks have no jump leniency at reaching the end of their tracks.

### ISSUE THREAD

**Issue by vivianlonging** [CommunalHelper/CommunalHelper#77]

**Comment by vivianlonging** [comment]
Reference: https://discordapp.com/channels/788175180613550080/807883040646758402/892126351476269117 (SJ - coding council)
https://streamable.com/xs2iff

**Comment by catapillie** [comment]
Fixed in 4661a83606f7511c3451eadc60030426f9f5ea14.
