### ISSUE TITLE
Chained Falling Blocks Stalling

### ISSUE THREAD

**Issue by KAEERRRA** [CommunalHelper/CommunalHelper#81]
- [N] My mods and Everest install are up to date.
- [Y] I have recreated the bug with *only* CommunalHelper OR a minimum number of other mods enabled.

**Describe the bug**
Chain falling blocks have a set fall time instead of having the same fall behavior as other falling blocks. (This is also present in Viv Helper falling blocks)

**To Reproduce**
Step on and off or grab on and off a chain falling block quickly. It will stay still for longer than expected before faling.

**Expected behavior**
Normal falling blocks fall soon after they are stepped off of or let go of. This should remain the same for the chained ones.

**System Info(please complete the following information):**
 - OS: Windows

**Additional context**
Please keep this behavior as a legacy option after it is fixed. Someone has already used the bugged movement for their map.

**Comment by catapillie** [comment]
Should be fixed in e6f330ea3e2d8ad85993e556aa7ee8ebd7551961. Needs testing to make sure, so I'm not closing this issue yet, however the behavior looks fine to me.
