### ISSUE TITLE
Add floaty toggle for Track Switch Boxes

### ISSUE THREAD

**Issue by vivianlonging** [CommunalHelper/CommunalHelper#83]
Feature Request: Add floaty/sink toggle for Track Switch Boxes
Details: a toggle for the floaty and sink code implemented in C#; asked for by Ezel in Strawberry Jam for aesthetic purposes, since this was asked for both sink and floaty, this technically includes just covering over that part of the update code within an if statement

**Comment by earthwise01** [comment]
I've submitted a pull request that should address this here: https://github.com/CommunalHelper/CommunalHelper/pull/84
I've tested it using the FNA version of Celeste.
