### ISSUE TITLE
xaphan helper compat: you *can* grab the bottom of railed move blocks

### ISSUE THREAD

**Issue by microlith57** [CommunalHelper/CommunalHelper#89]
on the gamebanana page:

> The both mode turns on all three sides. (No you can't grab the bottom!)

but with xaphan helper magnetic ceilings, you can grab the bottoms of things. indeed, magnetting onto the bottom of a zip mover will trigger it.
it seems reasonable, then, that grabbing the bottom of a railed move block with vertical movement enabled and a magnetic ceiling attached should allow you to move it around.

**Comment by catapillie** [comment]
how would one check if the block is grabbed from the bottom? that seems like a good idea that i could look into!

**Comment by microlith57** [comment]
see https://discord.com/channels/403698615446536203/514006912115802113/926255136593043476

**Comment by microlith57** [comment]
@catapillie i have implemented xaphan's method
